# sch2mpc_schedule_parser.py
# This program converts the schedule generated by the scheduler to the input required by mpc which is uses at reference

import sys
import json
import csv

def convert_to_csv(robot_data):
    csv_data = []
    
    for robot in robot_data['robots']:
        robot_name = f'R_{robot["name"]}'
        path = robot['path']
        
        for i in range(len(path)):
            node_name = f'd_{path[i]["name"]}'
            eta = int(path[i]["time"])
            
            csv_data.append([robot_name, node_name, eta])
    
    return csv_data

def write_csv(csv_data, file_name='output.csv'):
    with open(file_name, 'w', newline='') as csv_file:
        csv_writer = csv.writer(csv_file)
        csv_writer.writerow(['robot_id', 'node_id', 'ETA'])
        csv_writer.writerows(csv_data)

if __name__ == '__main__':
    # checking command line args
    if len(sys.argv) < 2:
        sys.exit("usage error: missing input file path example: ./output/scheduler_result.json")

    if len(sys.argv) < 3:
        sys.exit("usage error: missing output file path example: ./output/mpc_input.csv")

    # Specify the path to your JSON file
    in_json_file_path = sys.argv[1]
    out_json_file_path = sys.argv[2]

    # Open the file and load the JSON data
    with open(in_json_file_path, 'r') as file:
        json_data = json.load(file)
    
    csv_data = convert_to_csv(json_data)
    write_csv(csv_data, out_json_file_path)
    print("Output dumped to: {}".format(out_json_file_path))
